jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: |
          apt-get update -qq
          apt-get install build-essential autoconf libtool-bin flex bison -y
          autoreconf -i
          ./configure
          make && make check
